#!/usr/bin/env php
<?php

define('BASE_PATH', __DIR__);
define('APP_PATH', BASE_PATH . '/app');
define('PUBLIC_PATH', BASE_PATH . '/public');
define('RESOURCES_PATH', BASE_PATH . '/resources');
define('ROUTES_PATH', BASE_PATH . '/routes');
define('STORAGE_PATH', BASE_PATH . '/storage');

chdir(BASE_PATH);

if (is_file(BASE_PATH . '/vendor/autoload.php')) {
    require_once BASE_PATH . '/vendor/autoload.php';
}
require_once BASE_PATH . '/src/Cyron/Support/Env.php';
\Cyron\Support\Env::load(BASE_PATH . '/.env');
require_once BASE_PATH . '/src/Cyron/Libs/jdf.php';
require_once __DIR__ . '/app/autoload.php';
require_once __DIR__ . '/src/Cyron/helpers.php';
require_once __DIR__ . '/src/Cyron/Lady/LegacyConverter.php';
require_once __DIR__ . '/src/Cyron/Database/Db.php';
require_once __DIR__ . '/src/Cyron/Database/Model.php';
require_once __DIR__ . '/src/Cyron/Database/Migration.php';
require_once __DIR__ . '/src/Cyron/Database/Migrator.php';
require_once __DIR__ . '/src/Cyron/Database/Schema.php';
require_once __DIR__ . '/app/Http/Controller.php';
require_once __DIR__ . '/src/Cyron/Http/ErrorBag.php';
require_once __DIR__ . '/src/Cyron/Http/Storage.php';
require_once __DIR__ . '/app/Http/Middleware.php';

require_once __DIR__ . '/src/Cyron/Console/Colors.php';
require_once __DIR__ . '/src/Cyron/Console/Input.php';
require_once __DIR__ . '/src/Cyron/Console/CommandLoader.php';
require_once __DIR__ . '/src/Cyron/Console/Console.php';
require_once __DIR__ . '/src/Cyron/Scheduling/ScheduledTask.php';
require_once __DIR__ . '/src/Cyron/Scheduling/Schedule.php';
require_once __DIR__ . '/src/Cyron/Scheduling/Scheduler.php';
require_once __DIR__ . '/src/Cyron/Queue/Job.php';
require_once __DIR__ . '/src/Cyron/Queue/Queue.php';
require_once __DIR__ . '/src/Cyron/Queue/Worker.php';
require_once __DIR__ . '/src/Cyron/Events/EventDispatcher.php';
require_once __DIR__ . '/src/Cyron/Events/ListenerJob.php';
require_once __DIR__ . '/src/Cyron/Events/Event.php';

\Cyron\Console\CommandLoader::load();

$console = new \Cyron\Console\Console();
$console->run();
