#!/usr/bin/env php
<?php

define('BASE_PATH', __DIR__);
define('APP_PATH', BASE_PATH . '/app');
define('PUBLIC_PATH', BASE_PATH . '/public');
define('RESOURCES_PATH', BASE_PATH . '/resources');
define('ROUTES_PATH', BASE_PATH . '/routes');
define('STORAGE_PATH', BASE_PATH . '/storage');

require_once APP_PATH . '/Core/Env.php';
\App\Core\Env::load(BASE_PATH . '/.env');
require_once APP_PATH . '/Libs/jdf.php';
require_once __DIR__ . '/app/autoload.php';
require_once __DIR__ . '/app/helpers.php';
require_once __DIR__ . '/app/str.php';
require_once __DIR__ . '/app/router.php';
require_once __DIR__ . '/app/lady.php';
require_once __DIR__ . '/app/Request.php';
require_once __DIR__ . '/app/database/Db.php';
require_once __DIR__ . '/app/database/Model.php';
require_once __DIR__ . '/app/database/Migration.php';
require_once __DIR__ . '/app/Http/Controller.php';
require_once __DIR__ . '/app/Http/ErorrBag.php';
require_once __DIR__ . '/app/Http/Storage.php';
require_once __DIR__ . '/app/Http/Middleware.php';

if (!file_exists(__DIR__ . '/cli/Console.php')) {
    mkdir(__DIR__ . '/cli', 0777, true);
}
require_once __DIR__ . '/cli/Console.php';
require_once __DIR__ . '/cli/Input.php';

if (!file_exists(__DIR__ . '/cli/Commands')) {
    mkdir(__DIR__ . '/cli/Commands', 0777, true);
}
foreach (glob(__DIR__ . '/cli/Commands/*.php') as $file) {
    require_once $file;
}

$console = new Console();
$console->run();
