<?php
return [
    'users' => [
        'model'    => \App\Models\User::class,
        'label'    => 'کاربران',
        'columns'  => ['id', 'name', 'email', 'role', 'created_at'],
        'searchable' => ['name', 'email'],
        'form' => [
            'name'     => 'text|required',
            'email'    => 'email|required|unique',
            'password' => 'password|required|min:6|confirmed',
            'role'     => 'select:admin,user,editor',
            'status'   => 'select:active,inactive',
        ],
    ],
    'roles' => [
        'model'      => \App\Models\Role::class,
        'label'      => 'نقش‌ها',
        'icon'       => 'shield',
        'columns'    => ['id', 'name', 'slug', 'description', 'is_system', 'is_active', 'priority'],
        'searchable' => ['name', 'slug', 'description'],
        'sortable'   => ['id', 'priority', 'is_active'],
        'filters'    => ['is_active' => [1 => 'فعال', 0 => 'غیرفعال'], 'is_system' => [1 => 'سیستمی', 0 => 'کاربری']],
        'form' => [
            'name'        => 'text|required|max:191',
            'slug'        => 'text|required|max:191|unique:roles,slug',
            'description' => 'textarea|nullable',
            'is_system'   => 'checkbox',
            'is_active'   => 'checkbox:1',
            'priority'    => 'number|integer|min:0',
        ],
        'relations' => [
            'permissions' => [
                'type' => 'belongsToMany',
                'label' => 'دسترسی‌ها',
                'pivot' => 'role_permissions',
            ],
            'users' => [
                'type' => 'belongsToMany',
                'label' => 'کاربران',
                'pivot' => 'user_roles',
            ],
        ],
    ],
    'permissions' => [
        'model'      => \App\Models\Permission::class,
        'label'      => 'دسترسی‌ها',
        'icon'       => 'key',
        'columns'    => ['id', 'name', 'slug', 'group', 'module', 'is_critical'],
        'searchable' => ['name', 'slug', 'group', 'module'],
        'sortable'   => ['id', 'group', 'module'],
        'filters'    => ['group' => ['user', 'role', 'content', 'system'], 'is_critical' => [1 => 'بحرانی', 0 => 'عادی']],
        'form' => [
            'name'         => 'text|required|max:191',
            'slug'         => 'text|required|max:191|unique:permissions,slug',
            'group'        => 'text|required|max:191',
            'module'       => 'text|nullable|max:191',
            'description'  => 'textarea|nullable',
            'is_critical'  => 'checkbox',
        ],
    ],
    'books' => [
        'model'    => \App\Models\Book::class,
        'label'    => 'کتاب‌ها',
        'icon' => 'book',
        'columns'  => ['id', 'title', 'author_name', 'price'],
        'searchable' => ['title', 'author_name'],
        'form' => [
            'title'       => 'text|required',
            'slug'        => 'text|required|unique',
            'author_name' => 'text',
            'price'       => 'number',
            'cover'       => 'file|image',
            'description' => 'textarea',
        ],
    ],
    'subscriptions' => [
        'model' => \App\Models\Subscription::class,
        'label' => 'اشتراک‌ها',
        'icon' => 'gem',
        'columns' => ['id', 'name', 'price', 'duration', 'allows_download'],
        'searchable' => ['name', 'description'],
        'form' => [
            'name' => 'text|required',
            'description' => 'textarea|nullable',
            'price' => 'number|required',
            'duration' => 'number|required',
            'allows_download' => 'checkbox',
            'counts_download' => 'number',
            'offer' => 'number',
        ],
    ],
    'discounts' => [
        'model' => \App\Models\Discount::class,
        'label' => 'تخفیف‌ها و کدها',
        'icon' => 'percent',
        'columns' => ['id', 'name', 'code', 'type', 'value', 'applies_to', 'target_type', 'is_active'],
        'searchable' => ['name', 'code'],
        'form' => [
            'name' => 'text|required',
            'code' => 'text|nullable|unique',
            'type' => 'select:percent,fixed|required',
            'value' => 'number|required',
            'applies_to' => 'select:all,book,subscription|required',
            'target_type' => 'select:all,book,category,author,subscription|required',
            'target_id' => 'number|nullable',
            'min_amount' => 'number',
            'max_discount' => 'number|nullable',
            'starts_at' => 'text|nullable',
            'ends_at' => 'text|nullable',
            'usage_limit' => 'number|nullable',
            'is_active' => 'checkbox',
        ],
    ],
    'articles' => [
        'model' => \App\Models\Article::class,
        'label' => 'مقالات وبلاگ',
        'icon' => 'file-text',
        'columns' => ['id', 'title', 'status', 'published_at'],
        'searchable' => ['title', 'slug', 'excerpt'],
        'form' => [
            'title' => 'text|required',
            'slug' => 'text|required|unique',
            'excerpt' => 'textarea|nullable',
            'content' => 'textarea|nullable',
            'cover' => 'text|nullable',
            'status' => 'select:draft,published|required',
            'published_at' => 'text|nullable',
        ],
    ],
    'forum_categories' => [
        'model' => \App\Models\ForumCategory::class,
        'label' => 'دسته‌بندی‌های انجمن',
        'icon' => 'folder-open',
        'columns' => ['id', 'name', 'slug', 'sort_order', 'created_at'],
        'searchable' => ['name', 'slug', 'description'],
        'sortable' => ['id', 'sort_order', 'created_at'],
        'form' => [
            'name' => 'text|required|max:100',
            'slug' => 'text|required|max:100|unique:forum_categories,slug',
            'description' => 'textarea|nullable',
            'sort_order' => 'number|integer|min:0',
        ],
    ],
];