@extends('admin.layout')
@section('content')
<div dir="rtl" class="space-y-5">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><span class="text-xs font-semibold text-indigo-600">ANALYTICS</span><h1 class="text-2xl font-bold text-slate-800">تحلیل واقعی پلتفرم</h1><p class="text-sm text-slate-500">آمار فعالیت‌های ثبت‌شده از {{ $from }} تا {{ $to }}</p></div><div class="flex gap-3"><a class="rounded-lg border border-slate-300 px-4 py-2 text-sm" href="{{ route('admin.analytics.export') }}?{{ http_build_query(['from' => $from, 'to' => $to]) }}">خروجی CSV</a><a class="text-sm text-indigo-600" href="{{ route('admin.activities.index') }}">Activity Explorer</a></div></div>
    <form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3"><label class="text-sm text-slate-600">از تاریخ<input type="date" name="from" value="{{ $from }}" class="mt-1 block w-full rounded-lg border-slate-300"></label><label class="text-sm text-slate-600">تا تاریخ<input type="date" name="to" value="{{ $to }}" class="mt-1 block w-full rounded-lg border-slate-300"></label><button class="self-end rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white" type="submit">به‌روزرسانی</button></form>
    <div class="grid gap-4 md:grid-cols-4"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><span class="text-sm text-slate-500">کاربران فعال</span><strong class="mt-2 block text-2xl text-slate-800">{{ count($activeUsers) }}</strong></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><span class="text-sm text-slate-500">کل رویدادها</span><strong class="mt-2 block text-2xl text-slate-800">{{ array_sum(array_column($chart, 'value')) }}</strong></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><span class="text-sm text-slate-500">خریدها</span><strong class="mt-2 block text-2xl text-slate-800">{{ $purchases }}</strong></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><span class="text-sm text-slate-500">درآمد</span><strong class="mt-2 block text-2xl text-slate-800">{{ number_format($revenue) }}</strong></div></div>
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="font-bold text-slate-800">روند فعالیت روزانه</h2><span class="text-xs text-slate-400">{{ $from }} تا {{ $to }}</span></div><div class="flex h-56 items-end gap-1 overflow-x-auto border-b border-slate-200">@foreach($chart as $point)<div class="flex min-w-5 flex-1 flex-col items-center justify-end gap-1" title="{{ $point['label'] }}: {{ $point['value'] }}"><span class="text-[10px] text-slate-500">{{ $point['value'] ?: '' }}</span><div class="w-full rounded-t bg-indigo-500" style="height: {{ $point['height'] }}%"></div><small class="text-[9px] text-slate-400">{{ $point['label'] }}</small></div>@endforeach</div></section>
    @if(!empty($metrics))<section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold text-slate-800">شاخص‌های سفارشی</h2><div class="grid gap-3 md:grid-cols-4">@foreach($metrics as $metric)<div class="rounded-lg bg-slate-50 p-4"><span class="text-sm text-slate-500">{{ $metric['label'] }}</span><strong class="mt-1 block text-xl text-slate-800">{{ is_float($metric['value']) ? number_format($metric['value'], 2) : number_format($metric['value']) }}</strong></div>@endforeach</div></section>@endif
</div>
@endsection